### ISSUE TITLE
Fix to Configuration in ReadMe.txt

### ISSUE THREAD

**Issue by ken-clifton** [kaufmannr/mod_spamhaus_new#1]
Thank you so much for sharing this Rainer!  This works well and greatly reduces malicious actors. I have one correction that I found with the Apache API module name in the ReadMe.txt file.

In the text document: ReadMe.txt, "configuration" section, 
**Line 56:** change the LoadModule command to:
LoadModule spamhaus_new_module /usr/lib/apache2/modules/mod_spamhaus_new.so

This will fix an error where Apache will not restart due to an invalid command.

Thanks again!
Ken Clifton

**Comment by kaufmannr** [comment]
Dear Ken, thank you for the feedback!
